var electronics = [
  {
    key: "B00OSTKZWM",
    category: "Electronics",
    name: " Cell Phone, Dual SIM,Android 4.4 (White)",
    img: "https://images-na.ssl-images-amazon.com/images/I/51VCP05020L._AC_US218_.jpg",
    price: 57,
  },
  {
    key: "B01H2E0J5M",
    category: "Electronics",
    name: "16 GB - Black - Prime Exclusive - with Lockscreen ",
    img: "https://images-na.ssl-images-amazon.com/images/I/416TS-ODxfL._AC_US218_.jpg",
    price: 59,
    shipping: 7.99,
  },
  {
    key: "B0713WPJKX",
    category: "Electronics",
    name: "High Speed USB2.0 for Samsung Bluetooth Speaker-3 ",
    img: "https://images-na.ssl-images-amazon.com/images/I/61+-qmTKy8L._AC_US218_.jpg",
    price: 10,
    shipping: 3.99,
  },
  {
    key: "B01LPZD1N6",
    category: "Electronics",
    name: "Touchscreen 2Din Android Car Navigation Stereo ",
    img: "https://images-na.ssl-images-amazon.com/images/I/51xI8gJTNYL._AC_US218_.jpg",
    price: 164,
    shipping: 0,
  },
  {
    key: "B016F3M7OM",
    category: "Electronics",
    name: "Home Camera Wireless IP Security",
    img: "https://images-na.ssl-images-amazon.com/images/I/314hcoZg2JL._AC_US218_.jpg",
    price: 39,
    shipping: 3.99,
  },
  {
    key: "B01KVIN26O",
    category: "Electronics",
    name: "Cell Phone Camera Lens - TURATA 2 in 1 Professional HD Camera",
    img: "https://images-na.ssl-images-amazon.com/images/I/41wyZE9sWLL._AC_US218_.jpg",
    price: 11,
    shipping: 3.99,
  },
  {
    key: "B00UV6I8QQ",
    category: "Electronics",
    name: "Nikon Coolpix L340 20.2MP Digital Camera ",
    img: "https://images-na.ssl-images-amazon.com/images/I/41VVqVvKuNL._AC_US218_.jpg",
    price: 148,
    shipping: 3.99,
  },
  {
    key: "B00W68DSWQ",
    category: "Electronics",
    name: "Nikon COOLPIX L340 Digital Camera",
    img: "https://images-na.ssl-images-amazon.com/images/I/61yFYo02UzL._AC_US218_.jpg",
    price: 239,
    shipping: 7.99,
  },

  {
    key: "B071SF41Y9",
    category: "Electronics",
    name: "Microsoft Surface Pro (Intel Core i5)",
    img: "https://images-na.ssl-images-amazon.com/images/I/418g6Q3eTHL._AC_US218_.jpg",
    price: 10,
    shipping: 7.99,
  },
  {
    key: "B01N5P6TJW",
    category: "Electronics",
    name: 'Samsung Chromebook 3, 11.6"',
    img: "https://images-na.ssl-images-amazon.com/images/I/41XCWymAVaL._AC_US218_.jpg",
    price: 169,
    shipping: 7.99,
  },
  {
    key: "B01M8J68W0",
    category: "Electronics",
    name: "Kayond Bule Rose Pattern 12-13 inch Canvas laptop sleeve ",
    img: "https://images-na.ssl-images-amazon.com/images/I/51zDiHyaE1L._AC_US218_.jpg",
    price: 11,
    shipping: 3.99,
  },
  {
    key: "B072TY6LZL",
    category: "Electronics",
    name: "Microsoft Surface Laptop 13.5 inch Screen Protector",
    img: "https://images-na.ssl-images-amazon.com/images/I/51YGz9inR9L._AC_US218_.jpg",
    price: 33,
    shipping: 3.99,
  },
];

export default electronics;
